import Head from "next/head";
import { useState } from "react";

export default function AddCoursePage() {
  const [name, setName] = useState("");
  const [shortDescription, setShortDescription] = useState("");
  const [date, setDate] = useState("");
  const [language, setLanguage] = useState("");
  const [purpose, setPurpose] = useState("");
  const [chapters, setChapters] = useState([]);
  const [requirement, setRequirement] = useState("");
  const [description, setDescription] = useState("");
  const [target, setTarget] = useState("");
  const [price, setPrice] = useState("");
  const [promotion, setPromotion] = useState("");
  const [info, setInfo] = useState("");
  const [categories, setCategories] = useState([]);

  const handleSubmit = (event) => {
    event.preventDefault();
    // TODO: add code to handle form submission
  };

  const handleChapterChange = (index, value) => {
    const newChapters = [...chapters];
    newChapters[index] = value;
    setChapters(newChapters);
  };

  const handleAddChapter = () => {
    setChapters([...chapters, ""]);
  };

  return (
    <>
    <Head>
       <title>Udemy Register Page</title>
       <meta name="description" content="Generated by create next app" />
       <meta name="viewport" content="width=device-width, initial-scale=1" />
       <link rel="icon" href="/favicon.ico" />
     </Head>
    <div className="min-h-screen bg-gray-100 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
      <div className="sm:mx-auto sm:w-full sm:max-w-md">
        <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
          AddCoursePage
        </h2>
      </div>

      <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
        <div className="bg-white py-10 px-6 shadow sm:rounded-lg sm:px-10">
          <form onSubmit={handleSubmit}>
            <div className="mb-6">
              <label htmlFor="name" className="block font-bold mb-1">
                Name
              </label>
              <input
                type="text"
                id="name"
                name="name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="block w-full border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              />
            </div>

            <div className="mb-6">
              <label
                htmlFor="short-description"
                className="block font-bold mb-1"
              >
                Short Description
              </label>
              <textarea
                id="short-description"
                name="short-description"
                value={shortDescription}
                onChange={(e) => setShortDescription(e.target.value)}
                rows={2}
                className="block w-full border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              />
            </div>

            <div className="mb-6">
              <label htmlFor="date" className="block font-bold mb-1">
                Date
              </label>
              <input
                type="date"
                id="date"
                name="date"
                value={date}
                onChange={(e) => setDate(e.target.value)}
                className="block w-full border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              />
            </div>

            <div className="mb-6">
              <label htmlFor="language" className="block font-bold mb-1">
                Language
              </label>
              <input
                type="text"
                id="language"
                name="language"
                value={language}
                onChange={(e) => setLanguage(e.target.value)}
                className="block w-full border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              />
            </div>
            <div className="mb-6">
              <label htmlFor="purpose" className="block font-bold mb-1">
                Purpose
              </label>
              <textarea
                id="purpose"
                name="purpose"
                value={purpose}
                onChange={(e) => setPurpose(e.target.value)}
                rows={2}
                className="block w-full border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              />
            </div>
            {chapters.map((chapter, index) => (
              <div className="mb-6" key={index}>
                <label
                  htmlFor={`chapter-${index}`}
                  className="block font-bold mb-1"
                >
                  Chapter {index + 1}
                </label>
                <div className="flex">
                  <input
                    type="text"
                    id={`chapter-${index}`}
                    name={`chapter-${index}`}
                    value={chapter}
                    onChange={(e) => handleChapterChange(index, e.target.value)}
                    className="flex-1 border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                  />
                  {index === chapters.length - 1 && (
                    <button
                      type="button"
                      onClick={handleAddChapter}
                      className="ml-2 rounded-md border border-gray-300 py-2 px-3"
                    >
                      Add Chapter
                    </button>
                  )}
                </div>
              </div>
            ))}

            <div className="mb-6">
              <label htmlFor="requirement" className="block font-bold mb-1">
                Requirement
              </label>
              <textarea
                id="requirement"
                name="requirement"
                value={requirement}
                onChange={(e) => setRequirement(e.target.value)}
                rows={2}
                className="block w-full border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              />
            </div>

            <div className="mb-6">
              <label htmlFor="description" className="block font-bold mb-1">
                Description
              </label>
              <textarea
                id="description"
                name="description"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                rows={4}
                className="block w-full border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              />
            </div>

            <div className="mb-6">
              <label htmlFor="target" className="block font-bold mb-1">
                Target
              </label>
              <textarea
                id="target"
                name="target"
                value={target}
                onChange={(e) => setTarget(e.target.value)}
                rows={2}
                className="block w-full border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              />
            </div>

            <div className="mb-6">
              <label htmlFor="price" className="block font-bold mb-1">
                Price
              </label>
              <input
                type="number"
                id="price"
                name="price"
                value={price}
                onChange={(e) => setPrice(e.target.value)}
                className="block w-full border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              />
            </div>
            <div className="mb-6">
              <label htmlFor="promotion" className="block font-bold mb-1">
                Promotion
              </label>
              <textarea
                id="promotion"
                name="promotion"
                value={promotion}
                onChange={(e) => setPromotion(e.target.value)}
                rows={2}
                className="block w-full border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              />
            </div>

            <div className="mb-6">
              <label htmlFor="info" className="block font-bold mb-1">
                Additional Information
              </label>
              <textarea
                id="info"
                name="info"
                value={info}
                onChange={(e) => setInfo(e.target.value)}
                rows={2}
                className="block w-full border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              />
            </div>

            <div className="mb-6">
              <label htmlFor="categories" className="block font-bold mb-1">
                Categories
              </label>
              <select
                id="categories"
                name="categories"
                value={categories}
                onChange={(e) =>
                  setCategories(
                    Array.from(
                      e.target.selectedOptions,
                      (option) => option.value
                    )
                  )
                }
                
                className="block w-full border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
              >
                <option value="Development">Development</option>
                <option value="Design">Design</option>
                <option value="Marketing">Marketing</option>
                <option value="Business">Business</option>
              </select>
            </div>
          
            <button
              type="submit"
              className="bg-blue-500 text-white py-2 px-4  rounded  hover:bg-blue-800 w-full"
            >
              Submit
            </button>
          
          </form>
        </div>
      </div>
    </div>
    </>
  );
}
