name: Backend Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Run FastAPI application
      run: |
        cd backend
        uvicorn main:app --reload > /dev/null 2>&1 & echo $! > "app.pid"
        sleep 3

    - name: Run tests
      env:
        APP_PID: $(cat "backend/app.pid")
      run: |
        cd backend
        pytest
      continue-on-error: true

    - name: Stop FastAPI application
      env:
        APP_PID: $(cat "backend/app.pid")
      run: |
        kill $APP_PID
